spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: "umc9th"

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PW}

  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true

jwt:
  secret: ${JWT_TOKEN_KEY}
  access-token-validity: 3600000  # 1시간 (밀리초)
  refresh-token-validity: 604800000  # 7일 (밀리초)